# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.

title: SupeRails Blog
description: >- # this means to ignore newlines until "baseurl:"
  Ruby on Rails tips & tricks, courses, screencasts.
  Also my adventures in hackathons, startups, teaching online.
#baseurl: "" # the subpath of your site, e.g. /blog
url: "https://blog.corsego.com"

remote_theme: jekyll/minima

disqus:
  shortname: corsego

links_to_prev_next: true

minima:
  skin: classic
  date_format: "%a, %b %-d, %Y"
  social_links:
    - { platform: github, user_url: "https://github.com/yshmarov/" }
    - { platform: linkedin, user_url: "https://www.linkedin.com/in/yshmarov/" }
    - { platform: mastodon, user_url: "https://ruby.social/@yarotheslav/" }
    - { platform: twitter, user_url: "https://twitter.com/yarotheslav/" }
    - { platform: youtube, user_url: "https://www.youtube.com/@SupeRails/" }

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-pwa-plugin
  - jekyll-tagging-related_posts
  - jekyll-target-blank
  - jekyll-postfiles
  - jekyll-og-image

tagline: Ruby on Rails tips and tricks

feed:
  posts_limit: 1000

author:
  name: Yaroslav Shmarov
  email: hello@superails.com

#logo: /assets/corsego-saas-tree-logo.png

permalink: "/:title"

pwa:
  enabled: true # Optional
  sw_src_filepath: service-worker.js # Optional
  sw_dest_filename: service-worker.js # Optional
  dest_js_directory: assets/js # Required
  precache_recent_posts_num: 5 # Optional
  precache_glob_directory: / # Optional
  precache_glob_patterns: # Optional
    - "{js,css,fonts}/**/*.{js,css,eot,svg,ttf,woff}"
    - index.html
  precache_glob_ignores: # Optional
    - sw-register.js
    - "fonts/**/*"

og_image:
  output_dir: "assets/images/og"
  image: "/assets/static-pages/yaro-cindy.jpg"
  domain: "superails.com"
  border_bottom:
    width: 20
    fill:
      - "#820C02"
      - "#A91401"
      - "#D51F06"
      - "#DE3F24"
      - "#EDA895"

#jekyll_admin:
#  hidden_links:
#    - posts
#    - pages
#    - staticfiles
#    - datafiles
#    - configuration

# SEO tag useful info
# https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/usage.md

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
