# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Corsego blog
description: >- # this means to ignore newlines until "baseurl:"
  Blog about Ruby on Rails (courses, tutorials, tips).
  Also my adventures in hackathons, startups, teaching online.
#baseurl: "" # the subpath of your site, e.g. /blog
url: "https://blog.corsego.com"
twitter_username: yaro_the_slav
github_username:  yshmarov

# Build settings
theme: minima
#remote_theme: jekyll/minima

disqus:
  shortname: corsego

minima:
  skin: dark
  #skin: solarized-dark
  #date_format: "%b %-d, %Y"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

tagline: Ruby on Rails and Indie Hacking

author:
  name: Yaroslav Shmarov
  email: hello@corsego.com

logo: /assets/corsego-saas-tree-logo.png
social:
  name: Yaroslav Shmarov
  links:
    - https://twitter.com/yaro_the_slav
    - https://www.facebook.com/yshmarov
    - https://www.linkedin.com/in/yshmarov
    - https://github.com/yshmarov

permalink: "/:title"

google_analytics: UA-164140784-2

# SEO tag useful info
# https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/usage.md

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
